version: '3'
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    extra_hosts:
      - "host.docker.internal:host-gateway"